# Generated by Django 3.2.9 on 2022-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assesment_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
