# Generated by Django 3.2.9 on 2022-01-27 06:55

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_userform_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intro_vid',
            field=models.FileField(blank=True, null=True, upload_to='Assesment/static/introvedios/', validators=[accounts.validators.vid_size]),
        ),
    ]
