# Generated by Django 3.2.9 on 2022-01-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_intro_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduation_spcl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_graduation_spcl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='graduation',
            field=models.CharField(choices=[('1', 'B.Tech'), ('2', 'B.Com'), ('3', 'BBA'), ('4', 'B.E'), ('5', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_graduation',
            field=models.CharField(choices=[('1', 'M.Tech'), ('2', 'MBA'), ('3', 'ME'), ('4', 'M.Sc'), ('4', 'Others')], max_length=100),
        ),
    ]
