# Generated by Django 3.2.9 on 2022-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220128_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduation',
            field=models.CharField(choices=[('1', 'B.Tech'), ('2', 'B.Com'), ('3', 'BBA'), ('4', 'B.E'), ('5', 'Others')], default='Select Graduation', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_graduation',
            field=models.CharField(choices=[('1', 'M.Tech'), ('2', 'MBA'), ('3', 'ME'), ('4', 'M.Sc'), ('4', 'Others')], default='Select Post_Graduation', max_length=100),
        ),
    ]
