# Generated by Django 4.0.2 on 2022-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220202_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduation',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Com', 'B.Com'), ('BBA', 'BBA'), ('B.E', 'B.E'), ('Others', 'Others')], default='Select Graduation', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_graduation',
            field=models.CharField(choices=[('M.Tech', 'M.Tech'), ('MBA', 'MBA'), ('ME', 'ME'), ('M.Sc', 'M.Sc'), ('Not Applicable', 'Not Applicable')], default='Select Post_Graduation', max_length=100),
        ),
    ]
