# Generated by Django 4.0.2 on 2022-03-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='assesment_taken',
            new_name='answer_saved',
        ),
    ]
