# Generated by Django 4.0.2 on 2022-03-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_assesment_taken_customuser_answer_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assesment_taken',
            field=models.BooleanField(default=False),
        ),
    ]
