# Generated by Django 4.0.2 on 2022-03-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('attempt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=750, null=True)),
                ('op1', models.CharField(blank=True, max_length=100, null=True)),
                ('op2', models.CharField(blank=True, max_length=100, null=True)),
                ('op3', models.CharField(blank=True, max_length=100, null=True)),
                ('op4', models.CharField(blank=True, max_length=100, null=True)),
                ('ans', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, default='a', max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sel_ans', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('percent', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
