# Generated by Django 4.0.2 on 2022-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0002_remove_quesmodel_sel_ans_quesmodel_saved_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='saved_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
