# Generated by Django 4.0.2 on 2022-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0003_alter_quesmodel_saved_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='score',
            field=models.FloatField(default=False),
        ),
    ]
