# Generated by Django 4.0.2 on 2022-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0004_categories_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('Logical Reasoning', 'Logical Reasoning'), ('Verbal Ability', 'Verbal Ability'), ('Financial Question', 'Financial Question'), ('Personality Assessment', 'Personality Assessment')], default='Select Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='difficulty',
            field=models.CharField(choices=[('a', 'a')], default='Select Difficulty', max_length=100),
        ),
    ]
