# Generated by Django 4.0.2 on 2022-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0005_alter_quesmodel_category_alter_quesmodel_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('Logical Reasoning', 'Logical Reasoning'), ('Verbal Ability', 'Verbal Ability'), ('Financial Question', 'Financial Question'), ('Personality Assessment', 'Personality Assessment')], default='Logical Reasoning', max_length=100),
        ),
    ]
