# Generated by Django 4.0.2 on 2022-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0006_alter_quesmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='ans',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='para_answer',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='questiontype',
            field=models.CharField(choices=[('multiple choice', 'multiple choice'), ('single answer', 'single answer'), ('paragraph answer', 'paragraph answer')], default='Select Qtype', max_length=100),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='single_answer',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
