# Generated by Django 4.0.2 on 2022-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0008_quesmodel_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='para_answer',
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='questiontype',
            field=models.CharField(choices=[('multiple choice', 'multiple choice'), ('single answer', 'single answer')], default='Select Qtype', max_length=100),
        ),
    ]
